// srcServer/engines/objectLibrary.ts

export const objectLibrary = {
  vehículo: [
    { id: "Ambulancia", name: "Ambulancia", sprite_name: "ambulance.png" },
    { id: "Buggy", name: "Buggy", sprite_name: "buggy.png" },
    { id: "Bus", name: "Bus", sprite_name: "bus.png" },
    { id: "Autobús Escolar", name: "Autobús Escolar", sprite_name: "bus_school.png" },
    { id: "Convertible", name: "Convertible", sprite_name: "convertible.png" },
    { id: "Bicicleta", name: "Bicicleta", sprite_name: "cycle.png" },
    { id: "Camión de Bomberos", name: "Camión de Bomberos", sprite_name: "firetruck.png" },
    { id: "Fórmula 1", name: "Fórmula 1", sprite_name: "formula.png" },
    { id: "Camioneta Hotdog", name: "Camioneta Hotdog", sprite_name: "hotdog.png" },
    { id: "Kart", name: "Kart", sprite_name: "kart.png" },
    { id: "Policía", name: "Policía", sprite_name: "police.png" },
    { id: "Antidisturbios", name: "Antidisturbios", sprite_name: "riot.png" },
    { id: "Scooter", name: "Scooter", sprite_name: "scooter.png" },
    { id: "Sedan", name: "Sedan", sprite_name: "sedan.png" },
    { id: "Sedan Azul", name: "Sedan Azul", sprite_name: "sedan_blue.png" },
    { id: "Sedan Clásico", name: "Sedan Clásico", sprite_name: "sedan_vintage.png" },
    { id: "Deportivo Convertible", name: "Deportivo Convertible", sprite_name: "sports_convertible.png" },
    { id: "Deportivo Verde", name: "Deportivo Verde", sprite_name: "sports_green.png" },
    { id: "Deportivo de Carreras", name: "Deportivo de Carreras", sprite_name: "sports_race.png" },
    { id: "Deportivo Rojo", name: "Deportivo Rojo", sprite_name: "sports_red.png" },
    { id: "Deportivo Amarillo", name: "Deportivo Amarillo", sprite_name: "sports_yellow.png" },
    { id: "SUV", name: "SUV", sprite_name: "suv.png" },
    { id: "SUV Cerrado", name: "SUV Cerrado", sprite_name: "suv_closed.png" },
    { id: "SUV Verde", name: "SUV Verde", sprite_name: "suv_green.png" },
    { id: "SUV Grande", name: "SUV Grande", sprite_name: "suv_large.png" },
    { id: "SUV Militar", name: "SUV Militar", sprite_name: "suv_military.png" },
    { id: "SUV de Viaje", name: "SUV de Viaje", sprite_name: "suv_travel.png" },
    { id: "Taxi", name: "Taxi", sprite_name: "taxi.png" },
    { id: "Grúa", name: "Grúa", sprite_name: "towtruck.png" },
    { id: "Tractor", name: "Tractor", sprite_name: "tractor.png" },
    { id: "Transporte", name: "Transporte", sprite_name: "transport.png" },
    { id: "Camión", name: "Camión", sprite_name: "truck.png" },
    { id: "Camión con Remolque", name: "Camión con Remolque", sprite_name: "truck_trailer.png" },
    { id: "Cabina de Camión", name: "Cabina de Camión", sprite_name: "truckcabin.png" },
    { id: "Cabina Clásica", name: "Cabina Clásica", sprite_name: "truckcabin_vintage.png" },
    { id: "Camión Oscuro", name: "Camión Oscuro", sprite_name: "truckdark.png" },
    { id: "Camión de Reparto", name: "Camión de Reparto", sprite_name: "truckdelivery.png" },
    { id: "Camión Cisterna", name: "Camión Cisterna", sprite_name: "trucktank.png" },
    { id: "Remolque Cisterna", name: "Remolque Cisterna", sprite_name: "trucktank_trailer.png" },
    { id: "Furgoneta", name: "Furgoneta", sprite_name: "van.png" },
    { id: "Furgoneta Plana", name: "Furgoneta Plana", sprite_name: "van_flat.png" },
    { id: "Furgoneta Grande", name: "Furgoneta Grande", sprite_name: "van_large.png" },
    { id: "Furgoneta Pequeña", name: "Furgoneta Pequeña", sprite_name: "van_small.png" },
    { id: "Puesto Ambulante", name: "Puesto Ambulante", sprite_name: "vendor.png" },
    { id: "Auto Clásico", name: "Auto Clásico", sprite_name: "vintage.png" }
  ],
  persona: [
    { id: "Hombre", name: "Hombre", sprite_name: "man.png" },
    { id: "Mujer", name: "Mujer", sprite_name: "woman.png" },
    { id: "Hombre Caminando 1", name: "Hombre Caminando", sprite_name: "man_walk1.png" },
    { id: "Hombre Caminando 2", name: "Hombre Caminando", sprite_name: "man_walk2.png" },
    { id: "Mujer Caminando 1", name: "Mujer Caminando", sprite_name: "woman_walk1.png" },
    { id: "Mujer Caminando 2", name: "Mujer Caminando", sprite_name: "woman_walk2.png" },
    { id: "Hombre Señalando", name: "Hombre Señalando", sprite_name: "man_point.png" },
    { id: "Mujer Señalando", name: "Mujer Señalando", sprite_name: "woman_point.png" }
  ]
};